In [5]:
import numpy as np

In [46]:
d = np.linspace(5, 15, 3)
d

array([ 5., 10., 15.])

In [47]:
m = 1.5
tau_m = m / d
zeta = 1 / tau_m
zeta

array([ 3.33333333,  6.66666667, 10.        ])

In [48]:
zeta

array([ 3.33333333,  6.66666667, 10.        ])

In [ ]:
[1.2+i*0.5 for dk in]