In [1]:
import numpy as np

In [21]:
N_bonds = 127
N_walks = 10000
bond_length=.97

In [22]:
def get_walk(N: int, bond_length: float):
    phis = np.random.uniform(low=0, high=2 * np.pi, size=N)
    thetas = np.random.uniform(low=0, high=np.pi, size=N)
    rs = bond_length * np.vstack([
        np.sin(thetas) * np.cos(phis),
        np.sin(thetas) * np.sin(phis),
        np.cos(thetas)
    ]).T
    return rs

walks = [get_walk(N=N_bonds, bond_length=bond_length) for _ in range(N_walks)]
walks[0]

array([[ 0.5069027 ,  0.04527047, -0.82577251],
       [ 0.27170008, -0.30038859, -0.88138854],
       [ 0.39753484,  0.55403861,  0.68986033],
       [-0.03753006,  0.56966801,  0.78420014],
       [-0.92996904,  0.06562915,  0.26786267],
       [ 0.22315844,  0.15516467, -0.93114136],
       [-0.84137271, -0.45456479,  0.16236631],
       [ 0.06931593,  0.10971751, -0.96127903],
       [ 0.20783532, -0.11706015,  0.94021349],
       [ 0.18394656,  0.09134089, -0.9480087 ],
       [ 0.4155934 ,  0.87203132, -0.08799714],
       [ 0.4422243 ,  0.33561823, -0.79542321],
       [ 0.02806329, -0.0331994 , -0.96902541],
       [-0.57610561,  0.77840826,  0.05552391],
       [ 0.44711363,  0.6639632 , -0.54785241],
       [ 0.54791055, -0.01130931,  0.80035375],
       [ 0.22022255, -0.77823086,  0.53549861],
       [-0.03234211,  0.00630358, -0.96944018],
       [-0.05077019,  0.65119382,  0.71712551],
       [-0.45131694,  0.6801234 , -0.52406601],
       [ 0.39717216, -0.84824714, -0.252

In [23]:
def calculate_ete_vec(walk: np.ndarray) -> np.ndarray:
    return np.sum(walk, axis=0)

ete_vecs = [calculate_ete_vec(w) for w in walks]
ete_vecs

[array([  7.30903826,   4.61242349, -10.93708292]),
 array([11.26749604,  1.84875334,  3.27371233]),
 array([-0.44934913, -1.27374548,  8.47155373]),
 array([ 1.88130521,  2.26950128, -0.70998115]),
 array([ 1.62112552,  0.62605447, -2.77121077]),
 array([-5.43775364, -4.71414413, -7.40081041]),
 array([ -5.20297343,   5.5102496 , -18.80625152]),
 array([-3.74973271,  7.20177687,  1.83045096]),
 array([-2.60610786,  8.49574923,  6.50245541]),
 array([5.47585721, 3.78827846, 2.61828514]),
 array([-4.56055069, -4.9351612 , -0.01544078]),
 array([ 0.65460743, -4.21796352,  2.05434842]),
 array([-7.71451257, -4.89697621,  5.90846426]),
 array([ 6.35092048, -4.25468973,  0.90740827]),
 array([  4.97137659,  -2.92617243, -13.84536507]),
 array([ 1.69829321, -0.87109743, -5.27680131]),
 array([-2.49157619,  3.34184726, -5.36384043]),
 array([ -5.28999421, -10.1650646 ,   4.26659674]),
 array([  2.0559623 ,  -3.44532002, -11.67648576]),
 array([ 8.74105951,  7.67727933, -6.09662237]),
 array([

In [24]:
np.sum(ete_vecs, axis=0) / len(ete_vecs)

array([ 0.13720811,  0.01451117, -0.04488708])